### ISSUE TITLE
Does it work on Java 8 or not???

### ISSUE THREAD

**Issue by pierrelasse** [McModLauncher/modlauncher#126]
![image](https://github.com/McModLauncher/modlauncher/assets/76223390/365a99d0-8347-4715-a419-674befb8a47a)

https://github.com/McModLauncher/modlauncher/blob/4612c65f67a5ccb8308d95da28e8d83b77303cf7/src/main/java/cpw/mods/modlauncher/Launcher.java#L64
Clearly not a Java 8 feature ^

**Comment by Su5eD** [comment]
See https://github.com/McModLauncher/modlauncher/issues/69

**Comment by pierrelasse** [comment]
??? They only talk about licensing stuff

**Comment by Matyrobbrt** [comment]
ModLauncher v11 uses Java 21. Prior versions (like 10) used 17.

**Comment by pierrelasse** [comment]
Why does it say it works on java 8?

**Comment by pierrelasse** [comment]
Is there any project that lets me do mixin things outside of minecraft on java 8? This is so stupid. I searched everywhere but found nothing.
