### ISSUE TITLE
Transformer voting and ordering

### ISSUE THREAD

**Issue by sp614x** [McModLauncher/modlauncher#32]
Currently the transformer voting is a bit pointless as it doesn't have any useful context on which to base the vote. The ITransformerVotingContext is empty, casting to VotingContext only gives the class name and sha1 which is not enough when working with modified classes.

Ideally the voting would need a full context (parsed node, transformers applied, transformers left, etc.). The parsed node should be read-only or it should be recreated for each transformer to avoid side effects.

It is clear that the general recommendation is to write core mods in JavaScript and only as absolutely last resort fall back to transformers. The examples below are general, not specific to transformers. The JS core mods could also benefit from adding vote support in a similar way.

Transformer ordering is important as there are some transformers that may want to:
- execute first (optifine)
- execute after another transformer (optifabric after optifine)
- delay or apply different patches depending on the other transformers (replaymod with or without optifine). 
 - execute last, in order to have the last word

In order for a transformer to specify its order preferences the vote results could be extended.

Vote results:
 - NOW - must patch in this round (strong yes)
 - YES - can patch in this round
 - COULD - could patch in this round, but prefer to skip (weak yes)
 - NO - can't patch in this round
 - NEVER - can't patch in any round (skip all subsequent rounds)
 - FAIL - catastrophic failure, abort transformation

Winners are NOW (highest priority), YES (normal priority) and COULD (lowest priority).

Normal transformers should only use YES/NO.
Complex transformers could additionally use NOW/COULD/NEVER to select the round at which to be applied relative to other transformers.

The decision to crash (FAIL) should be left to the transformer as it is the only one that knows if the patch is required or not. A round which ends with all transformers voting NO shouldn't cause any special action.

After the class transformation is complete, all transformers should be informed by calling "boolean transformFinished(Node, List<Transformer> applied, Set<Transformer> skipped)". The transformer can return false if its required patch hasn't been applied or if the Node state is broken in some way. This should abort the class transforming and crash similar to FAIL.

Currently the voting is per class and the transformer can't make general decisions until the transforming has started, which may be too late (some classes may have already been patched in a wrong way). For example a transformer may deactivate itself early or switch to a different set of patches if it sees that another specific transformer is active. 

To solve this a new ITransformer method can be added `boolean init(Map<TransformerID,<Set<ClassNames>>)` so the transformer knows which other transformers are going to patch which classes. Returning false would deactivate the transformer and remove it from the voting.

At the beginning the list of transformers should be sorted in a stable way (most trivial is by transformer id). All subsequent operations (init, voting, application of equal winners) should be done in this order. This would immensly simplify bug reproduction and bug fixing as the same set of transformers would always behave in the same way.

**Comment by sp614x** [comment]
The transformers currently have no own IDs and there may be several transformers per transformation service (which has an ID). This means that transformers can't be uniquely identified.
Switching to one transformer per service or adding transformer IDs could fix this.

**Comment by cpw** [comment]
The second concern: around "init" would be better solved by modifying the TransformationService itself. If you need a different set based on environmental factors, both initialize and onLoad are called prior to ModLauncher fetching the list of transformers. If there is insufficient information in those methods (and the Environment they receive) then we can look at extending both of them. In fact, the environment will be how you tell FML/Forge that you exist. I'm going to add a standard "Modifier" hook where you can add any mod information you wish.

**Comment by cpw** [comment]
Please review the 3.x versions of modlauncher. Should be good to go. Suggest validating that you're in that version by checking the api package's specificationversion, before doing anything else.

**Comment by Technici4n** [comment]
Should be good, as cpw said 4 years ago. :)
