### ISSUE TITLE
OpenJ9 detection fails for certain builds of the VM

### ISSUE THREAD

**Issue by Hubry** [McModLauncher/modlauncher#67]
Encountered in vectorwing/FarmersDelight#190, which seems to make the modded game crash because of a typetools bug.

https://github.com/cpw/modlauncher/blob/3cf110cd0b2a5bcd8a44057fd0513e38a4b06f97/src/main/java/cpw/mods/modlauncher/ValidateLibraries.java#L29

The builds used by these users, coming from [AdoptOpenJDK](https://adoptopenjdk.net) seem to contain the string `OpenJ9` in properties `java.vm.name`, `java.vm.info` and `java.vm.vendor`, but not the checked `java.vendor` (which is `AdoptOpenJDK`).

An answer to a question about detecting OpenJ9 on Adopt's github repo [here](https://github.com/AdoptOpenJDK/openjdk-build/issues/1188#issuecomment-513922314) seems to point at `java.vm.name` for this.

**Comment by sciwhiz12** [comment]
Fixed by #96, merged as 9b69c82a176c0896b264ab167813a52adc6f12cb.
