### ISSUE TITLE
Use checker framework instead of jsr305

### ISSUE THREAD

**Issue by liach** [McModLauncher/modlauncher#7]

**Comment by cpw** [comment]
Please explain?

**Comment by jamierocks** [comment]
https://github.com/google/guava/issues/2960 details why jsr305 is no longer in favor.

**Comment by liach** [comment]
The dependency itself would not be a huge burden: it is just a line like https://github.com/KyoriPowered/lunar/blob/master/build.gradle#L33
`compile 'org.checkerframework:checker-qual:2.5.1'`

**Comment by zml2008** [comment]
This issue is no longer applicable -- ModLauncher now uses JetBrains' annotations for nullability.
