### ISSUE TITLE
Modlauncher can't detect interfaces of transformer parents

### ISSUE THREAD

**Issue by Su5eD** [McModLauncher/modlauncher#97]
Suppose you have a base `ITransformer` class with a subclass for each type:

`public abstract class BaseTransformer<T> implements ITransformer<T>`
├─ `public class ClassTransformer extends BaseTransformer<ClassNode>`
├─ `public class MethodTransformer extends BaseTransformer<MethodNode>`
└─ `public class FieldTransformer extends BaseTransformer<FieldNode>`

Modlauncher [expects](https://github.com/McModLauncher/modlauncher/blob/5dfb7451a7525e49f33c7f2facbec66665803bc6/src/main/java/cpw/mods/modlauncher/TransformationServiceDecorator.java#L78) the interface to be implemented in the transformer class itself.
Therefore running this structure will result in an [exception](https://github.com/McModLauncher/modlauncher/blob/5dfb7451a7525e49f33c7f2facbec66665803bc6/src/main/java/cpw/mods/modlauncher/TransformationServiceDecorator.java#L84).

**Comment by cpw** [comment]
arguably, this is a trivial fix in the code: implement on the class itself, rather than the parent. It's a bit untidier but would result in functional code.

**Comment by Su5eD** [comment]
Fixed by #102
